server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    #向eureka注册中心注册
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #eureka注册中心注册地址
      #可以只写1个注册中心的地址只要写的那个激活然后写的那个注册中心与其他注册中心集群并互相注册，其他未再次填写的注册中心仍然可以访问到该服务
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka

