server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #匹配在注册中心中服务的名称
          uri: lb:CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Cookie=username,sherlock
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: payment_route2
          uri: http://localhost:8001
          predicates:
            Path=/payment/discovery #断言,路径相匹配的进行路由

eureka:
  client:
    # 表示是否从eureka服务器获得注册信息
    fetch-registry: true
    # 向eureka注册中心注册
    register-with-eureka: true
    service-url:
      #eureka注册中心注册地址
      #可以只写1个注册中心的地址只要写的那个激活然后写的那个注册中心与其他注册中心集群并互相注册，其他未再次填写的注册中心仍然可以访问到该服务
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service