server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 服务注册集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    # 在eureka注册中心显示的名称
    instance-id: order80
    # 鼠标放在这个名称上时(参考eureka.instance.instance-id)左下角显示的内容是否显示真实IP作为前缀
    prefer-ip-address: true
#ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间(不知道为啥不起作用)
  #ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  #ConnectTimeout: 5000

# 可以在控制台打印每次访问的详细信息，配合com.sherlock.springcloud.config.FeignLogConfig.FeignLoggerLevel使用
logging:
  level:
    com.sherlock.springcloud.service.PaymentFeignService: debug